FROM node:alpine

USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node

COPY --chown=node:node ./package.json ./

RUN npm install

COPY --chown=node:node . ./
COPY --chown=node:node ./public ./public
CMD ["npm", "run", "start"]

